version: 2

updates:
    # Maintain dependencies for the JavaScript package
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          eslint:
              patterns:
                  - 'eslint'
                  - 'eslint-*'
                  - '@eslint/*'
                  - '@eslint-community/*'
                  - '@typescript-eslint/*'
          vitest:
              patterns:
                  - 'vitest'
                  - '@vitest/coverage-v8'
          lodash-debounce:
              patterns:
                  - 'lodash.debounce'
                  - '@types/lodash.debounce'
      ignore:
          - dependency-name: '@types/vscode'

    # Maintain dependencies for GitHub Actions
    - package-ecosystem: 'github-actions'
      directory: '/'
      schedule:
          interval: 'weekly'
      groups:
          artifact-actions:
              patterns:
                  - 'actions/upload-artifact'
                  - 'actions/download-artifact'
