changelog:
    exclude:
        labels:
            - chore
            - ci
            - docs
            - refactor
            - ignore-for-release
            - skip-changelog
        authors:
            - dependabot[bot]
    categories:
        - title: Breaking Changes
          labels:
              - breaking
        - title: Features and Enhancements
          labels:
              - feat
        - title: Fixes
          labels:
              - fix
