changelog:
    exclude:
        labels:
            - chore
            - ci
            - dependencies
            - documentation
            - ignore-for-release
            - skip-changelog
        authors:
            - dependabot[bot]
    categories:
        - title: Breaking changes
          labels:
              - breaking-change
              - breaking
              - semver-major
        - title: Features and Enhancements
          labels:
              - enhancement
              - feature
              - feat
              - semver-minor
        - title: Fixes
          labels:
              - bug
              - bugfix
              - fix
              - semver-patch
