name: ci

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_call:

env:
    NODE_VERSION: 22.x

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - id: get-app-token
              uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc
              with:
                  app_id: ${{ secrets.TOPO_ACCESS_APP_ID }}
                  private_key: ${{ secrets.TOPO_ACCESS_APP_PRIVATE_KEY }}
            - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
            - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - name: Install dependencies
              env:
                  GITHUB_TOKEN: ${{ steps.get-app-token.outputs.token }}
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Build
              run: npm run build

    test:
        needs: build
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest
        steps:
            - id: get-app-token
              uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc
              with:
                  app_id: ${{ secrets.TOPO_ACCESS_APP_ID }}
                  private_key: ${{ secrets.TOPO_ACCESS_APP_PRIVATE_KEY }}
            - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
            - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - name: Install NPM dependencies
              run: npm ci
              env:
                  GITHUB_TOKEN: ${{ steps.get-app-token.outputs.token }}
            - name: Download other dependencies
              run: npm run download
            - name: Store npm-debug.log
              if: always()
              uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
              with:
                  name: npm-errors-${{ matrix.os }}
                  path: ./npm-debug.log
                  if-no-files-found: ignore
            - name: Unit Test
              run: npm run test
