name: ci

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

env:
    NODE_VERSION: 20.x

jobs:
    configure-ci:
        name: Configure CI
        runs-on: ubuntu-latest
        steps:
            - id: get-app-token
              uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc
              with:
                  app_id: ${{ secrets.TOPO_ACCESS_APP_ID }}
                  private_key: ${{ secrets.TOPO_ACCESS_APP_PRIVATE_KEY }}
            - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  registry-url: https://npm.pkg.github.com
                  always-auth: true
            - name: Install dependencies
              env:
                  GITHUB_TOKEN: ${{ steps.get-app-token.outputs.token }}
                  NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
              run: npm ci
            - name: Lint
              run: npm run lint
            - name: Build
              run: npm run build

    test:
        needs: configure-ci
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os:
                    - ubuntu-latest
                    - windows-latest
        steps:
            - id: get-app-token
              uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc
              with:
                  app_id: ${{ secrets.TOPO_ACCESS_APP_ID }}
                  private_key: ${{ secrets.TOPO_ACCESS_APP_PRIVATE_KEY }}
            - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  registry-url: https://npm.pkg.github.com
                  always-auth: true
            - name: Install NPM dependencies
              run: npm ci
              env:
                  GITHUB_TOKEN: ${{ steps.get-app-token.outputs.token }}
                  NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
            - name: Download other dependencies
              run: npm run download
            - name: Store npm-debug.log
              if: always()
              uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
              with:
                  name: npm-errors-${{ matrix.os }}
                  path: ./npm-debug.log
                  if-no-files-found: ignore
            - name: Unit Test
              run: npm run test
            - name: Upload coverage report artifact
              if: matrix.os == 'ubuntu-latest'
              uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
              with:
                  name: unit-test-coverage
                  path: ./coverage
                  if-no-files-found: error
    publish-coverage:
        name: Publish Coverage
        needs:
            - test
            - configure-ci
        runs-on: [self-hosted, self-hosted-ubuntu-latest, x64, aws-debug-prod]
        steps:
            - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
            - name: Download coverage reports from artifacts
              uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
              with:
                  name: unit-test-coverage
                  path: coverage
            - name: Publish coverage report to Qlty
              uses: qltysh/qlty-action/coverage@v2.2.0
              with:
                  token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
                  files: coverage/lcov.info
                  skip-errors: false
