name: Release

on:
    workflow_dispatch:
        inputs:
            release-type:
                type: choice
                description: A new version is published with the corresponding version bump if not set to None.
                options:
                    - 'None'
                    - 'Pre-release'
                    - 'Patch'
                    - 'Minor'
                    - 'Major'
                default: 'None'

env:
    NODE_VERSION: 20.x
    PRE_RELEASE_FLAG: ${{ inputs.release-type == 'Pre-release' && '--pre-release' || '' }}

jobs:
    ci:
        uses: ./.github/workflows/ci.yaml
        secrets: inherit

    prepare-version:
        name: Prepare Version
        needs: ci
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.calculate-version.outputs.version }}
        steps:
            - id: get-app-token
              uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc
              with:
                  app_id: ${{ secrets.TOPO_ACCESS_APP_ID }}
                  private_key: ${{ secrets.TOPO_ACCESS_APP_PRIVATE_KEY }}
            - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  registry-url: https://npm.pkg.github.com
                  always-auth: true
            - name: Install NPM dependencies
              run: npm ci
              env:
                  GITHUB_TOKEN: ${{ steps.get-app-token.outputs.token }}
                  NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
            - name: Calculate Version
              id: calculate-version
              env:
                  RELEASE_TYPE: ${{ inputs.release-type }}
              run: |
                  VERSION=$(npm run calculate-new-version --silent)
                  echo "version=$VERSION" >> "$GITHUB_OUTPUT"
            - name: Update extension version
              if: steps.calculate-version.outputs.version
              run: npm version --no-git-tag-version ${{ steps.calculate-version.outputs.version }}
            - name: Update changelog version
              run: |
                  sed -i.bak -r "s/## \[?Unreleased\]?/## $VERSION/g" CHANGELOG.md
                  rm CHANGELOG.md.bak
              env:
                  VERSION: ${{ steps.calculate-version.outputs.version }}
            - name: Create version bump patch
              if: steps.calculate-version.outputs.version
              run: git diff > new-version.patch
            - name: Store version bump patch
              if: steps.calculate-version.outputs.version
              uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
              with:
                  name: new-version-patch
                  path: ./new-version.patch
                  if-no-files-found: error

    build:
        name: Build ${{ matrix.platform }}
        needs:
            - ci
            - prepare-version
        runs-on: ubuntu-latest
        strategy:
            matrix:
                platform:
                    - win32-x64
                    - linux-x64
                    - linux-arm64
                    - darwin-arm64
        steps:
            - id: get-app-token
              uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc
              with:
                  app_id: ${{ secrets.TOPO_ACCESS_APP_ID }}
                  private_key: ${{ secrets.TOPO_ACCESS_APP_PRIVATE_KEY }}
            - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  registry-url: https://npm.pkg.github.com
                  always-auth: true
            - name: Download version bump patch
              if: needs.prepare-version.outputs.version
              uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
              with:
                  name: new-version-patch
                  path: ~/patches
            - name: Apply version bump patch
              if: needs.prepare-version.outputs.version
              run: git apply ~/patches/new-version.patch
            - name: Install NPM dependencies
              env:
                  GITHUB_TOKEN: ${{ steps.get-app-token.outputs.token }}
                  NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
              run: npm ci
            - name: Download other dependencies
              run: npm run download
            - name: Package VSIX
              run: npm run package -- --target ${{ matrix.platform }} $PRE_RELEASE_FLAG
            - name: Upload VSIX
              uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4
              with:
                  name: vsix-package-${{ matrix.platform }}
                  path: ./*${{ matrix.platform }}*.vsix
                  retention-days: 1
                  if-no-files-found: error

    push-new-version:
        name: Push New Version
        needs:
            - prepare-version
            - build
        if: needs.prepare-version.outputs.version
        runs-on: ubuntu-latest
        outputs:
            release_commit: ${{ inputs.release-type == 'Pre-release' && github.sha || steps.commit-version.outputs.release_commit }}
        steps:
            - uses: actions/checkout@71cf2267d89c5cb81562390fa70a37fa40b1305e
            - name: Download version bump patch
              uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
              with:
                  name: new-version-patch
                  path: ~/patches
            - name: Apply version bump patch
              run: git apply ~/patches/new-version.patch
            - name: Set git config for Extensions Repo bot
              run: |
                  git config --global user.email "135710658+extensions-repo-access[bot]@users.noreply.github.com"
                  git config --global user.name "extensions-repo-access[bot]"
            - name: Commit new version
              id: commit-version
              run: |
                  git commit -a -m "${{ needs.prepare-version.outputs.version }}"
                  COMMIT=$(git rev-parse HEAD)
                  echo "release_commit=$COMMIT" >> "$GITHUB_OUTPUT"
            - name: Add "Unreleased" section to changelog
              run: |
                  echo "`sed -e "s/# Change Log/# Change Log\n\n## [Unreleased]/g" CHANGELOG.md`" > CHANGELOG.md
                  git commit -a -m "Add 'Unreleased' section to CHANGELOG.md [skip ci]"
            - name: Push changes
              if: inputs.release-type != 'Pre-release'
              run: git push

    release:
        name: Release
        needs:
            - prepare-version
            - build
        if: needs.prepare-version.outputs.version
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
              with:
                  path: artifacts
            - name: Release
              uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090
              with:
                  files: artifacts/*/*.vsix
                  tag_name: v${{ needs.prepare-version.outputs.version }}
                  target_commitish: ${{ needs.push-new-version.outputs.release_commit }}
                  prerelease: ${{ inputs.release-type == 'Pre-release' }}

    publish:
        name: Publish
        needs:
            - prepare-version
            - release
        if: needs.prepare-version.outputs.version && github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest
        steps:
            - uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53
              with:
                  name: vsix-package
                  path: artifacts
            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020
              with:
                  node-version: ${{ env.NODE_VERSION }}
            - name: Publish to VS Code Marketplace
              run: npx vsce publish -i artifacts/*.vsix -p ${{secrets.VS_MARKETPLACE_TOKEN}} $PRE_RELEASE_FLAG
            - name: Publish to Open VSX
              run: npx ovsx@0.8.0 publish -i artifacts/*.vsix -p ${{secrets.OPEN_VSX_TOKEN}} $PRE_RELEASE_FLAG
